In [25]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import os
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression

from sklearn import metrics
from sklearn import preprocessing

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC

In [26]:
#Import Data
train=pd.read_csv("train_2kmZucJ.csv")
test=pd.read_csv("test_oJQbWVk.csv")

In [27]:
#Removing unwanted elements from the tweet column
train["tweet"]=train['tweet'].str.replace(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*pic.twitter.com',"")
test["tweet"]=test['tweet'].str.replace(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*pic.twitter.com',"")

In [28]:
#Splitting into x & y
y=train["label"]
x=train["tweet"]

In [29]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [30]:
#Vectorizing the text file
vect = CountVectorizer(ngram_range=(2,2))
xtrain = vect.fit_transform(xtrain)
xtest= vect.transform(xtest)

In [31]:
#Using SVC algorithm
svc=SVC()
svc.fit(xtrain,ytrain)

C:\Users\Barath\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [32]:
ypred=svc.predict(xtest)
confusion_matrix(ytest,ypred)

array([[1159,    0],
       [ 425,    0]], dtype=int64)

In [33]:
accuracy_score(ytest,ypred)

0.7316919191919192

In [34]:
#Using Logistic Regression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)
ypred2=lr.predict(xtest)
accuracy_score(ytest,ypred2)

C:\Users\Barath\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8806818181818182

In [35]:
confusion_matrix(ytest,ypred2)

array([[1070,   89],
       [ 100,  325]], dtype=int64)

In [36]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [37]:
#Using Naive bayes theorm
nb= MultinomialNB()
nb.fit(xtrain,ytrain)
nbpred=nb.predict(xtest)
print("Accuracy score", accuracy_score(ytest,nbpred))
print(confusion_matrix(ytest,nbpred))

Accuracy score 0.8939393939393939
[[1061   98]
 [  70  355]]


In [38]:
#Using Random forest

rf= RandomForestClassifier()
rf.fit(xtrain,ytrain)
rfpred=rf.predict(xtest)
print("confusion matrix",confusion_matrix(ytest,rfpred))
print("Accuracy score", accuracy_score(ytest,rfpred))
print(confusion_matrix(ytest,rfpred))

C:\Users\Barath\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


confusion matrix [[1124   35]
 [ 275  150]]
Accuracy score 0.8042929292929293
[[1124   35]
 [ 275  150]]


In [39]:
# Since the accuracy of naive bayes is higher, proceeding with naive bayes 
a=list(test["tweet"])
test2 = vect.transform(a)

nbpred=nb.predict(test2)

In [40]:
test2

<1953x64731 sparse matrix of type '<class 'numpy.int64'>'
	with 16449 stored elements in Compressed Sparse Row format>

In [42]:
nbpred=pd.DataFrame(nbpred,columns=["label"])
test2=pd.concat((test,nbpred),axis=1)

In [46]:
test2=test2.drop(["tweet"],axis=1)

In [47]:
test2.to_csv("predicted values.csv")